### PR TITLE
#28.feature:create landing-page #28

### PR DESCRIPTION
**Pull request by shemalucien**
#### What does this PR do?

- Implements to create a landing page

#### Description of Task to be completed? 

- User can be able to see the landing page

#### How should this be manually tested?

- Clone the repo

- checkout to branch``ft-create-landing-page-28``

- Run `npm install` to install modules

- Run `npm  run dev:start` to start the development server

- Run `npm  run test:coverage` to run tests

#### What are the relevant Pivotal Tracker/Trello stories

- link to my pivotal tracker/tello/https://trello.com/c/4Cj9e1Ag/28-landing-page

#### Screenshots 
-N/A

#### Questions:
-N/A

### CODE REVIEW

**Review by gyssa-prince — DISMISSED** [review]
Increase the size of the logo like h-14 w-21

**Review by songa1 — COMMENTED** [review]
The buttonon the hero section is "TRACK BUS" not "SHOW MORE" and that bus should have a space on the right. Also remember to check buttons on hover. And footer copyright should not be that big.

**Review by arthurjunior250 — CHANGES_REQUESTED** [review]
-how it works cards have the same width, check the design
-your textArea is not fixed
-try to add space on the left and right side of your first page

**Review by Stevenkwizera06 — DISMISSED** [review]

**Review by arthurjunior250 — CHANGES_REQUESTED** [review]
-try to add border-radius on Get in touch with us (border),input field and textArea
-check the design your first page is not looking like the same page we have on the mockup design

**Review by Juleshb — DISMISSED** [review]

**Review by Stevenkwizera06 — DISMISSED** [review]

**Review by gyssa-prince — APPROVED** [review]

**Review by harerajo — APPROVED** [review]

**Review by songa1 — APPROVED** [review]

**Pull request merged**
